//ACTIONS
export const GET_CURRENCY = 'GET_CURRENCY'
//GETTERS
export const GET_STATE = 'GET_STATE';
//MUTATIONS
export const SET_CURRENCY = 'SER_CURRENCY'
export const SET_NEW_STATE = 'SET_NEW_STATE'
