//ACTIONS
export const GET_CURRENCY_TODAY = 'GET_CURRENCY_TODAY'
//GETTERS
export const GET_STATE = 'GET_STATE';
//MUTATIONS
export const GOT_CURRENCY = 'GOT_CURRENCY'
export const RESET_STATE = 'RESET_STATE'
